name: CI

on:
  push:
    branches:
      - main

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@22.3.0
        with:
          options: "--check --verbose"
          src: "./"
          version: "22.3.0"

  lint:
    name: Run linter
    needs: [format]
    runs-on: ubuntu-latest
    container:
      image: alpine/flake8:3.8.4
      options: --cpus="1"
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Run flake8
        run: flake8 ./ --append-config=./.flake8 --verbose

  test:
    name: Run tests
    needs: [format, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest tests/ -v
